### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by yuviDX** [kx3ez1/jiosaavn-downloader#1]
Please add feature to download all songs of an artist. If possible with language selection.

**Comment by sureshraj1** [comment]
it's downloading 100% working  but m4a file name coming bro can you check please ...

**Comment by NagireddyBharathReddy** [comment]
> it's downloading 100% working but m4a file name coming bro can you check please ...

 Yes, it is also an **audio format**. and it supports almost all music players

**Comment by NagireddyBharathReddy** [comment]
> Please add feature to download all songs of an artist. If possible with language selection.

Downloading **Artist Songs added**

**Comment by yuviDX** [comment]
why windows defender showing it as virus? [https://prnt.sc/vk6im3](url)

**Comment by NagireddyBharathReddy** [comment]
> why windows defender showing it as virus? [https://prnt.sc/vk6im3](url)

I also don't know why this happening..
I tried in my friends pc..windows defender is removing file..

- I will check and solve

**Comment by NagireddyBharathReddy** [comment]
> why windows defender showing it as virus? [https://prnt.sc/vk6im3](url)
checked but its showing 3more..
i think _anti-virus not configured properly_. And detecting as virus
Virus Total : [http://prnt.sc/vkhmnj](url)

**Comment by kx3ez1** [comment]
> why windows defender showing it as virus? [https://prnt.sc/vk6im3](url)

please compile source code 

https://github.com/kx3ez1/jiosaavan-api
